#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v3
# autospec commit: fae1327921d4
#
Name     : fftw
Version  : 3.3.10
Release  : 40
URL      : http://www.fftw.org/fftw-3.3.10.tar.gz
Source0  : http://www.fftw.org/fftw-3.3.10.tar.gz
Summary  : fast Fourier transform library
Group    : Development/Tools
License  : GPL-2.0
Requires: fftw-bin = %{version}-%{release}
Requires: fftw-info = %{version}-%{release}
Requires: fftw-lib = %{version}-%{release}
Requires: fftw-license = %{version}-%{release}
Requires: fftw-man = %{version}-%{release}
BuildRequires : gfortran
BuildRequires : openmpi-dev
BuildRequires : openssh
BuildRequires : texinfo

%description
FFTW is a free collection of fast C routines for computing the
Discrete Fourier Transform in one or more dimensions.  It includes
complex, real, symmetric, and parallel transforms, and can handle
arbitrary array sizes efficiently.  FFTW is typically faster than
other publically-available FFT implementations, and is even
competitive with vendor-tuned libraries.  (See our web page
http://fftw.org/ for extensive benchmarks.)  To achieve this
performance, FFTW uses novel code-generation and runtime
self-optimization techniques (along with many other tricks).

%package bin
Summary: bin components for the fftw package.
Group: Binaries
Requires: fftw-license = %{version}-%{release}

%description bin
bin components for the fftw package.


%package dev
Summary: dev components for the fftw package.
Group: Development
Requires: fftw-lib = %{version}-%{release}
Requires: fftw-bin = %{version}-%{release}
Provides: fftw-devel = %{version}-%{release}
Requires: fftw = %{version}-%{release}

%description dev
dev components for the fftw package.


%package info
Summary: info components for the fftw package.
Group: Default

%description info
info components for the fftw package.


%package lib
Summary: lib components for the fftw package.
Group: Libraries
Requires: fftw-license = %{version}-%{release}

%description lib
lib components for the fftw package.


%package license
Summary: license components for the fftw package.
Group: Default

%description license
license components for the fftw package.


%package man
Summary: man components for the fftw package.
Group: Default

%description man
man components for the fftw package.


%prep
%setup -q -n fftw-3.3.10
cd %{_builddir}/fftw-3.3.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1706211610
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -ffat-lto-objects -flto=auto "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -ffat-lto-objects -flto=auto "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -ffat-lto-objects -flto=auto "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
make  %{?_smp_mflags}  -n ||:


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -ffat-lto-objects -flto=auto "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -ffat-lto-objects -flto=auto "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -ffat-lto-objects -flto=auto "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1706211610
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fftw
cp %{_builddir}/fftw-%{version}/COPYING %{buildroot}/usr/share/package-licenses/fftw/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1 || :
cp %{_builddir}/fftw-%{version}/COPYRIGHT %{buildroot}/usr/share/package-licenses/fftw/1179609f742d35f1bcbf4ad694f371d64ee257ea || :
cp %{_builddir}/fftw-%{version}/doc/license.texi %{buildroot}/usr/share/package-licenses/fftw/ee99393637fb0b0a5df385deac9040c5305f38b2 || :
:
## install_append content
CFLAGS_IN="$CFLAGS -ffunction-sections -falign-functions=32 -O3 -flto -fno-semantic-interposition "
CXXFLAGS_IN="$CXXFLAGS -ffunction-sections -falign-functions=32 -O3 -flto -fno-semantic-interposition "
LDFLAGS_IN="$LDFLAGS"

for build in \
"single,--enable-float,--enable-sse2" \
"double,--enable-sse2" \
"long-double,--enable-long-double" \
"single-avx2,--enable-float,--enable-avx2,--enable-fma" \
"double-avx2,--enable-avx2,--enable-fma" \
"single-avx512,--enable-float,--enable-avx2,--enable-avx512,--enable-fma" \
"double-avx512,--enable-avx2,--enable-avx512,--enable-fma" \
"single-mpi,--enable-mpi,--enable-float,--enable-sse2"  \
"double-mpi,--enable-mpi,--enable-sse2" \
"long-double-mpi,--enable-mpi,--enable-long-double" \
"single-avx2-mpi,--enable-mpi,--enable-float,--enable-avx2,--enable-fma" \
"double-avx2-mpi,--enable-mpi,--enable-avx2,--enable-fma" \
"single-avx512-mpi,--enable-mpi,--enable-float,--enable-avx2,--enable-avx512,--enable-fma" \
"double-avx512-mpi,--enable-mpi,--enable-avx2,--enable-avx512,--enable-fma" ; \
do
skip_test=0
dir=$(echo $build | cut -d, -f1)
flags=$(echo $build | cut -d, -f2- | sed 's/,/ /g')
lib_path=$(echo $build | cut -d= -f1 --complement)

if echo $flags | grep -q avx512; then
export CFLAGS="$CFLAGS_IN -march=x86-64-v4 -Wl,-z,x86-64-v4"
export CXXFLAGS="$CXXFLAGS_IN -march=x86-64-v3 -Wl,-z,x86-64-v3"
export LDFLAGS="$LDFLAGS_IN -march=x86-64-v4"
grep -q 'avx512[^ ]*' /proc/cpuinfo || skip_test=1
elif echo $flags | grep -q avx2; then
export CFLAGS="$CFLAGS_IN -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS_IN -march=x86-64-v3 -Wl,-z,x86-64-v3"
export LDFLAGS="$LDFLAGS_IN -march=x86-64-v3"
grep -q 'avx2[^ ]*' /proc/cpuinfo || skip_test=1
else
export CFLAGS="$CFLAGS_IN"
export CXXFLAGS="$CXXFLAGS_IN"
export LDFLAGS="$LDFLAGS_IN"
fi

mkdir build-$dir
pushd build-$dir
../configure --disable-static --enable-shared --enable-threads --enable-openmp \
--prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib64 \
$flags
make V=1 %{?_smp_mflags}
if echo $flags | grep -q avx512; then
%make_install_v4
elif echo $flags | grep -q avx2; then
%make_install_v3
else
%make_install
fi
if [ $skip_test -eq 0 ]; then
echo "**** Testing $dir CFLAGS:$CFLAGS "
LD_LIBRARY_PATH=%{buildroot}$lib_path make check
fi
popd
done

/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx2   %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/fftw-wisdom
/V3/usr/bin/fftwf-wisdom
/V4/usr/bin/fftw-wisdom
/V4/usr/bin/fftwf-wisdom
/usr/bin/fftw-wisdom
/usr/bin/fftw-wisdom-to-conf
/usr/bin/fftwf-wisdom
/usr/bin/fftwl-wisdom

%files dev
%defattr(-,root,root,-)
/usr/include/fftw3-mpi.f03
/usr/include/fftw3-mpi.h
/usr/include/fftw3.f
/usr/include/fftw3.f03
/usr/include/fftw3.h
/usr/include/fftw3l-mpi.f03
/usr/include/fftw3l.f03
/usr/include/fftw3q.f03
/usr/lib64/cmake/fftw3/FFTW3Config.cmake
/usr/lib64/cmake/fftw3/FFTW3ConfigVersion.cmake
/usr/lib64/cmake/fftw3/FFTW3fConfig.cmake
/usr/lib64/cmake/fftw3/FFTW3fConfigVersion.cmake
/usr/lib64/cmake/fftw3/FFTW3lConfig.cmake
/usr/lib64/cmake/fftw3/FFTW3lConfigVersion.cmake
/usr/lib64/libfftw3.so
/usr/lib64/libfftw3_mpi.so
/usr/lib64/libfftw3_omp.so
/usr/lib64/libfftw3_threads.so
/usr/lib64/libfftw3f.so
/usr/lib64/libfftw3f_mpi.so
/usr/lib64/libfftw3f_omp.so
/usr/lib64/libfftw3f_threads.so
/usr/lib64/libfftw3l.so
/usr/lib64/libfftw3l_mpi.so
/usr/lib64/libfftw3l_omp.so
/usr/lib64/libfftw3l_threads.so
/usr/lib64/pkgconfig/fftw3.pc
/usr/lib64/pkgconfig/fftw3f.pc
/usr/lib64/pkgconfig/fftw3l.pc

%files info
%defattr(0644,root,root,0755)
/usr/share/info/fftw3.info
/usr/share/info/fftw3.info-1
/usr/share/info/fftw3.info-2

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libfftw3.so.3.6.10
/V3/usr/lib64/libfftw3_mpi.so.3.6.10
/V3/usr/lib64/libfftw3_omp.so.3.6.10
/V3/usr/lib64/libfftw3_threads.so.3.6.10
/V3/usr/lib64/libfftw3f.so.3.6.10
/V3/usr/lib64/libfftw3f_mpi.so.3.6.10
/V3/usr/lib64/libfftw3f_omp.so.3.6.10
/V3/usr/lib64/libfftw3f_threads.so.3.6.10
/V4/usr/lib64/libfftw3.so.3.6.10
/V4/usr/lib64/libfftw3_mpi.so.3.6.10
/V4/usr/lib64/libfftw3_omp.so.3.6.10
/V4/usr/lib64/libfftw3_threads.so.3.6.10
/V4/usr/lib64/libfftw3f.so.3.6.10
/V4/usr/lib64/libfftw3f_mpi.so.3.6.10
/V4/usr/lib64/libfftw3f_omp.so.3.6.10
/V4/usr/lib64/libfftw3f_threads.so.3.6.10
/usr/lib64/libfftw3.so.3
/usr/lib64/libfftw3.so.3.6.10
/usr/lib64/libfftw3_mpi.so.3
/usr/lib64/libfftw3_mpi.so.3.6.10
/usr/lib64/libfftw3_omp.so.3
/usr/lib64/libfftw3_omp.so.3.6.10
/usr/lib64/libfftw3_threads.so.3
/usr/lib64/libfftw3_threads.so.3.6.10
/usr/lib64/libfftw3f.so.3
/usr/lib64/libfftw3f.so.3.6.10
/usr/lib64/libfftw3f_mpi.so.3
/usr/lib64/libfftw3f_mpi.so.3.6.10
/usr/lib64/libfftw3f_omp.so.3
/usr/lib64/libfftw3f_omp.so.3.6.10
/usr/lib64/libfftw3f_threads.so.3
/usr/lib64/libfftw3f_threads.so.3.6.10
/usr/lib64/libfftw3l.so.3
/usr/lib64/libfftw3l.so.3.6.10
/usr/lib64/libfftw3l_mpi.so.3
/usr/lib64/libfftw3l_mpi.so.3.6.10
/usr/lib64/libfftw3l_omp.so.3
/usr/lib64/libfftw3l_omp.so.3.6.10
/usr/lib64/libfftw3l_threads.so.3
/usr/lib64/libfftw3l_threads.so.3.6.10

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fftw/1179609f742d35f1bcbf4ad694f371d64ee257ea
/usr/share/package-licenses/fftw/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1
/usr/share/package-licenses/fftw/ee99393637fb0b0a5df385deac9040c5305f38b2

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/fftw-wisdom-to-conf.1
/usr/share/man/man1/fftw-wisdom.1
/usr/share/man/man1/fftwf-wisdom.1
/usr/share/man/man1/fftwl-wisdom.1
